### ISSUE TITLE
Revisit ESLint rules

### ISSUE THREAD

**Issue by Siegrift** [api3dao/eslint-plugin-commons#13]
Add:
* https://github.com/gajus/eslint-plugin-zod
* Consistent quotes (", ', \`)

and look at disabled rules (and eslint-disable directives)  in signed API and airseeker repositories and consider disabling them in commons.

Remove:
* Disabled rules in signed API and Airseeker
* jest empty test -> test.todo (its annoying)

**Comment by dcroote** [comment]
Close now that the eslint plugin has [moved](https://github.com/api3dao/eslint-plugin-commons)? The referenced zod plugin doesn't look maintained anyway (11 commits total, last one 2 yrs ago).

**Comment by Siegrift** [comment]
I think this part:
> Remove:
Disabled rules in signed API and Airseeker
jest empty test -> test.todo (its annoying)

and also:

> Consistent quotes (", ', `)

is still valid. Let me move the issue instead.

**Comment by dcroote** [comment]
> Consistent quotes (", ', `)

Quotes are handled by prettier, no? I can try to use double quotes around some string and prettier in various repos will revert to single, for example.

**Comment by Siegrift** [comment]
Yeah, but it will not complain about  ``` `some-string` ``` - even if it could be `'some-string'` but that is not that important.
