### ISSUE TITLE
Add prefer early return rule

### ISSUE THREAD

**Issue by Siegrift** [api3dao/eslint-plugin-commons#17]
https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/prefer-early-return.md

I have to often comment this in the PR review. It would be nice to have this automated.

**Comment by dcroote** [comment]
I like this rule too- do you think it's fine to add the dependency for a single rule or instead copy just the file containing the rule and add the license?

**Comment by Siegrift** [comment]
Yeah, adding the dependency is better - feel free to check if there are some other rules we might like.

**Comment by dcroote** [comment]
What do you think about?
- https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/prefer-module-scope-constants.md
- https://github.com/Shopify/web-configs/blob/main/packages/eslint-plugin/docs/rules/no-ancestor-directory-import.md

**Comment by Siegrift** [comment]
Yep, look good.
