### ISSUE TITLE
Add "no-floating-promises" rule

### ISSUE THREAD

**Issue by Siegrift** [api3dao/eslint-plugin-commons#49]
See: https://typescript-eslint.io/rules/no-floating-promises/

I quite like this rule because it makes sure all promises are awaited or explicitly unhandled by doing `void somePromise`. This helped identify some bugs in the past, due to edge cases with promises (the unhandled ones).

Previously we were using all of the rules from "typescript-eslint", but now we're only using the recommended set. It might make sense to do a quick look whether there are other rules to be added.

**Comment by dcroote** [comment]
I like adding this because these types of bugs can be subtle and hard to identify
