### ISSUE TITLE
Disable unicorn/no-for-loop

### ISSUE THREAD

**Issue by Siegrift** [api3dao/eslint-plugin-commons#59]

**Comment by dcroote** [comment]
Any context for this?

**Comment by Siegrift** [comment]
It is a bit annoying because it completely forbids writing a for-loop. Sometimes the most cleaner way to write a piece of code is using a for loop (e.g. when the alternative is a complex reduce operation). I am a bit annoyed by disabling the rule each time.

**Comment by dcroote** [comment]
I'm a little confused because it does allow for loops: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-for-loop.md#pass

**Comment by Siegrift** [comment]
Yeah, but it does not allow the most basic one (with looping variable)

**Comment by dcroote** [comment]
The "pass" examples seem to be able to cover simple cases fine while avoiding painful off by one errors, but I don't care enough to keep arguing so it's in #64
